name: OrderService CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/OrderService/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/OrderService/**'

jobs:
  build:
    name: Build and Test Order Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Restore dependencies
        run: dotnet restore src/OrderService/OrderService.API/OrderService.API.csproj
      
      - name: Build
        run: dotnet build src/OrderService/OrderService.API/OrderService.API.csproj --no-restore --configuration Release